name: Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd hsn/registr-front
            git pull
            docker build -t hsn-app .
            docker run -p 3000:3000 -d hsn-app
#            cd hsn
#            git pull
#            docker stop hsn-app
#            docker rm hsn-app
#            docker rmi hsn-app
#            docker build -t hsn-app .
#            docker run -p 3000:3000 -d hsn-app