name: Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "deploy.tar"
          target: "~/app"

      - name: SSH and Build Docker Image
        uses: appleboy/ssh-action@v0.1.2
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.BACKEND_API_URL }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd ~/app
            docker build -t hsn-app .
            docker stop hsn-app || true
            docker rm hsn-app || true
            docker run -p 3000:3000 -d hsn-app